---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: pramodinfo2-dev
  namespace: dev
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  releaseName: pramodinfo2-dev
  chart:
    git: git@github.com:pramodbijani/gitops-helm
    path: charts/pramodinfo
    ref: master
  values:
    image: pramodbijani/podinfo:dev-2pdvcffx
    replicaCount: 1
    hpa:
      enabled: false
